# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Create 1.18.2 Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release Type'
        required: true
        default: 'alpha'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with: { fetch-depth: 0 }
      - name: "Setup JDK 17"
        uses: actions/setup-java@v2
        with: { distribution: "adopt", java-version: "17" }
      - name: "Get Commit Summary"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
          previousTag=$(git tag --sort=-creatordate | sed -n 2p)
          echo "previousTag : $previousTag"
          commitSummary="$(git log $previousTag..${{ github.ref }})"
          echo "::set-env name=COMMIT_SUMMARY::\"$commitSummary\""
      - name: "Build with Gradle"
        id: build
        run: "chmod +x gradlew && ./gradlew build"
      - name: "Create Release"
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          tag_name: "v${{ steps.build.outputs.version }}"
          release_name: "strawgolem-${{ steps.build.outputs.version }}"
          body: "${{env.COMMIT_SUMMARY}}"
          draft: false
          prerelease: "${{ inputs.releaseType != 'release' }}"
      - name: "Upload Fabric Release Assets"
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          release_id: "${{ steps.create_release.outputs.id }}"
          assets_path: "Fabric/build/libs"
      - name: "Upload Forge Release Assets"
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          release_id: "${{ steps.create_release.outputs.id }}"
          assets_path: "Forge/build/libs"
      - name: "Upload Fabric to CurseForge"
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: "Fabric/build/libs/strawgolem-${{ steps.build.outputs.version }}.jar"
          game_endpoint: "minecraft"
          relations: "fabric-api:requiredDependency"
          game_versions: "Minecraft 1.18.2,Java 17,Fabric"
          release_type: "${{ inputs.releaseType }}"
          project_id: "449768"
          token: "${{ secrets.CF_API_TOKEN }}"
      - name: "Upload Forge to CurseForge"
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: "Forge/build/libs/strawgolem-${{ steps.build.outputs.version }}.jar"
          game_endpoint: "minecraft"
          game_versions: "Minecraft 1.18.2,Java 17,Forge"
          release_type: "${{ inputs.releaseType }}"
          project_id: "387580"
          token: "${{ secrets.CF_API_TOKEN }}"
